# Generated by Django 5.2.7 on 2025-10-30 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("current_lat", models.FloatField()),
                ("current_lon", models.FloatField()),
                ("pickup_lat", models.FloatField()),
                ("pickup_lon", models.FloatField()),
                ("dropoff_lat", models.FloatField()),
                ("dropoff_lon", models.FloatField()),
                ("current_cycle_hours_used", models.FloatField(default=0)),
                ("planned_distance_m", models.FloatField(default=0)),
                ("planned_duration_s", models.FloatField(default=0)),
                ("geometry", models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="Stop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence_index", models.PositiveIntegerField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("fuel", "Fuel"),
                            ("break", "Break"),
                            ("rest", "Rest"),
                        ],
                        max_length=10,
                    ),
                ),
                ("at_distance_m", models.FloatField(default=0)),
                ("at_time_s", models.FloatField(default=0)),
                ("lat", models.FloatField(blank=True, null=True)),
                ("lon", models.FloatField(blank=True, null=True)),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stops",
                        to="planner.trip",
                    ),
                ),
            ],
            options={
                "ordering": ["sequence_index"],
            },
        ),
        migrations.CreateModel(
            name="ELDLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day_index", models.PositiveIntegerField()),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("sheet", models.JSONField(default=dict)),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eld_logs",
                        to="planner.trip",
                    ),
                ),
            ],
            options={
                "unique_together": {("trip", "day_index")},
            },
        ),
    ]
